meta_product_name: "Mixed by Mom Zorn"
meta_title: "Mixed by Mom Zorn - the Cocktail Queen"
meta_description: "Recipes for Karen's world famous elixirs, unveiled at last!"
meta_image: "about-page.png" # should exist in `app/assets/images/`
